
import './LexiTheme.scss';
export const lexiTheme = {
  blockCursor: 'SKEditorTheme__blockCursor',
  characterLimit: 'SKEditorTheme__characterLimit',
  code: 'SKEditorTheme__code',
  codeHighlight: {
    atrule: 'SKEditorTheme__tokenAttr',
    attr: 'SKEditorTheme__tokenAttr',
    boolean: 'SKEditorTheme__tokenProperty',
    builtin: 'SKEditorTheme__tokenSelector',
    cdata: 'SKEditorTheme__tokenComment',
    char: 'SKEditorTheme__tokenSelector',
    class: 'SKEditorTheme__tokenFunction',
    'class-name': 'SKEditorTheme__tokenFunction',
    comment: 'SKEditorTheme__tokenComment',
    constant: 'SKEditorTheme__tokenProperty',
    deleted: 'SKEditorTheme__tokenProperty',
    doctype: 'SKEditorTheme__tokenComment',
    entity: 'SKEditorTheme__tokenOperator',
    function: 'SKEditorTheme__tokenFunction',
    important: 'SKEditorTheme__tokenVariable',
    inserted: 'SKEditorTheme__tokenSelector',
    keyword: 'SKEditorTheme__tokenAttr',
    namespace: 'SKEditorTheme__tokenVariable',
    number: 'SKEditorTheme__tokenProperty',
    operator: 'SKEditorTheme__tokenOperator',
    prolog: 'SKEditorTheme__tokenComment',
    property: 'SKEditorTheme__tokenProperty',
    punctuation: 'SKEditorTheme__tokenPunctuation',
    regex: 'SKEditorTheme__tokenVariable',
    selector: 'SKEditorTheme__tokenSelector',
    string: 'SKEditorTheme__tokenSelector',
    symbol: 'SKEditorTheme__tokenProperty',
    tag: 'SKEditorTheme__tokenProperty',
    url: 'SKEditorTheme__tokenOperator',
    variable: 'SKEditorTheme__tokenVariable',
  },
  embedBlock: {
    base: 'SKEditorTheme__embedBlock',
    focus: 'SKEditorTheme__embedBlockFocus',
  },
  hashtag: 'SKEditorTheme__hashtag',
  heading: {
    h1: 'SKEditorTheme__h1',
    h2: 'SKEditorTheme__h2',
    h3: 'SKEditorTheme__h3',
    h4: 'SKEditorTheme__h4',
    h5: 'SKEditorTheme__h5',
    h6: 'SKEditorTheme__h6',
  },
  image: 'editor-image',
  indent: 'SKEditorTheme__indent',
  link: 'SKEditorTheme__link',
  list: {
    listitem: 'SKEditorTheme__listItem',
    listitemChecked: 'SKEditorTheme__listItemChecked',
    listitemUnchecked: 'SKEditorTheme__listItemUnchecked',
    nested: {
      listitem: 'SKEditorTheme__nestedListItem',
    },
    olDepth: [
      'SKEditorTheme__ol1',
      'SKEditorTheme__ol2',
      'SKEditorTheme__ol3',
      'SKEditorTheme__ol4',
      'SKEditorTheme__ol5',
    ],
    ul: 'SKEditorTheme__ul',
  },
  ltr: 'SKEditorTheme__ltr',
  mark: 'SKEditorTheme__mark',
  markOverlap: 'SKEditorTheme__markOverlap',
  paragraph: 'SKEditorTheme__paragraph',
  quote: 'SKEditorTheme__quote',
  rtl: 'SKEditorTheme__rtl',
  table: 'SKEditorTheme__table',
  tableAddColumns: 'SKEditorTheme__tableAddColumns',
  tableAddRows: 'SKEditorTheme__tableAddRows',
  tableCell: 'SKEditorTheme__tableCell',
  tableCellActionButton: 'SKEditorTheme__tableCellActionButton',
  tableCellActionButtonContainer:
    'SKEditorTheme__tableCellActionButtonContainer',
  tableCellEditing: 'SKEditorTheme__tableCellEditing',
  tableCellHeader: 'SKEditorTheme__tableCellHeader',
  tableCellPrimarySelected: 'SKEditorTheme__tableCellPrimarySelected',
  tableCellResizer: 'SKEditorTheme__tableCellResizer',
  tableCellSelected: 'SKEditorTheme__tableCellSelected',
  tableCellSortedIndicator: 'SKEditorTheme__tableCellSortedIndicator',
  tableResizeRuler: 'SKEditorTheme__tableCellResizeRuler',
  tableSelected: 'SKEditorTheme__tableSelected',
  text: {
    bold: 'SKEditorTheme__textBold',
    code: 'SKEditorTheme__textCode',
    italic: 'SKEditorTheme__textItalic',
    strikethrough: 'SKEditorTheme__textStrikethrough',
    subscript: 'SKEditorTheme__textSubscript',
    superscript: 'SKEditorTheme__textSuperscript',
    underline: 'SKEditorTheme__textUnderline',
    underlineStrikethrough: 'SKEditorTheme__textUnderlineStrikethrough',
  },
};
